// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function AddPullCommentReaction(arg1) {
  return window['go']['main']['App']['AddPullCommentReaction'](arg1);
}

export function AuthConnect(arg1) {
  return window['go']['main']['App']['AuthConnect'](arg1);
}

export function AuthDisconnect(arg1) {
  return window['go']['main']['App']['AuthDisconnect'](arg1);
}

export function AuthDisconnectOne(arg1) {
  return window['go']['main']['App']['AuthDisconnectOne'](arg1);
}

export function AuthStatus() {
  return window['go']['main']['App']['AuthStatus']();
}

export function AuthSwitchAccount(arg1) {
  return window['go']['main']['App']['AuthSwitchAccount'](arg1);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CloneRepo(arg1) {
  return window['go']['main']['App']['CloneRepo'](arg1);
}

export function ClosePull(arg1) {
  return window['go']['main']['App']['ClosePull'](arg1);
}

export function CopyRecentLogs(arg1) {
  return window['go']['main']['App']['CopyRecentLogs'](arg1);
}

export function CreatePullComment(arg1) {
  return window['go']['main']['App']['CreatePullComment'](arg1);
}

export function CreatePullReview(arg1) {
  return window['go']['main']['App']['CreatePullReview'](arg1);
}

export function CreatePullReviewComment(arg1) {
  return window['go']['main']['App']['CreatePullReviewComment'](arg1);
}

export function DeletePullBranch(arg1) {
  return window['go']['main']['App']['DeletePullBranch'](arg1);
}

export function DeletePullComment(arg1) {
  return window['go']['main']['App']['DeletePullComment'](arg1);
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function ExportLogs(arg1) {
  return window['go']['main']['App']['ExportLogs'](arg1);
}

export function FetchRepo(arg1) {
  return window['go']['main']['App']['FetchRepo'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetCheckUpdatesPref() {
  return window['go']['main']['App']['GetCheckUpdatesPref']();
}

export function GetCommitDetail(arg1) {
  return window['go']['main']['App']['GetCommitDetail'](arg1);
}

export function GetGitBinaryConfig() {
  return window['go']['main']['App']['GetGitBinaryConfig']();
}

export function GetGitGraph(arg1) {
  return window['go']['main']['App']['GetGitGraph'](arg1);
}

export function GetGitGraphAscii(arg1) {
  return window['go']['main']['App']['GetGitGraphAscii'](arg1);
}

export function GetPull(arg1) {
  return window['go']['main']['App']['GetPull'](arg1);
}

export function GetPullCommitsBehind(arg1) {
  return window['go']['main']['App']['GetPullCommitsBehind'](arg1);
}

export function GetPullFileDiff(arg1) {
  return window['go']['main']['App']['GetPullFileDiff'](arg1);
}

export function GetRepoById(arg1) {
  return window['go']['main']['App']['GetRepoById'](arg1);
}

export function GetUserPrefs(arg1) {
  return window['go']['main']['App']['GetUserPrefs'](arg1);
}

export function GetWorkspace() {
  return window['go']['main']['App']['GetWorkspace']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function IsRepoCloned(arg1) {
  return window['go']['main']['App']['IsRepoCloned'](arg1);
}

export function ListBranches(arg1) {
  return window['go']['main']['App']['ListBranches'](arg1);
}

export function ListIssues(arg1) {
  return window['go']['main']['App']['ListIssues'](arg1);
}

export function ListMilestones(arg1) {
  return window['go']['main']['App']['ListMilestones'](arg1);
}

export function ListPullCommentReactions(arg1) {
  return window['go']['main']['App']['ListPullCommentReactions'](arg1);
}

export function ListPullComments(arg1) {
  return window['go']['main']['App']['ListPullComments'](arg1);
}

export function ListPullCommits(arg1) {
  return window['go']['main']['App']['ListPullCommits'](arg1);
}

export function ListPullFiles(arg1) {
  return window['go']['main']['App']['ListPullFiles'](arg1);
}

export function ListPullReviewComments(arg1) {
  return window['go']['main']['App']['ListPullReviewComments'](arg1);
}

export function ListPullReviews(arg1) {
  return window['go']['main']['App']['ListPullReviews'](arg1);
}

export function ListPullTimeline(arg1) {
  return window['go']['main']['App']['ListPullTimeline'](arg1);
}

export function ListPulls(arg1) {
  return window['go']['main']['App']['ListPulls'](arg1);
}

export function ListRepos(arg1) {
  return window['go']['main']['App']['ListRepos'](arg1);
}

export function ListStarredBranches(arg1) {
  return window['go']['main']['App']['ListStarredBranches'](arg1);
}

export function ListWorkspaceRepos() {
  return window['go']['main']['App']['ListWorkspaceRepos']();
}

export function LogFrontend(arg1) {
  return window['go']['main']['App']['LogFrontend'](arg1);
}

export function LogGraph(arg1) {
  return window['go']['main']['App']['LogGraph'](arg1);
}

export function MergePull(arg1) {
  return window['go']['main']['App']['MergePull'](arg1);
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function OpenDesktopFolder() {
  return window['go']['main']['App']['OpenDesktopFolder']();
}

export function OpenDownloadPage() {
  return window['go']['main']['App']['OpenDownloadPage']();
}

export function OpenGitBinaryPicker() {
  return window['go']['main']['App']['OpenGitBinaryPicker']();
}

export function PullRepo(arg1) {
  return window['go']['main']['App']['PullRepo'](arg1);
}

export function PullRepoByProjectId(arg1) {
  return window['go']['main']['App']['PullRepoByProjectId'](arg1);
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function RemovePullCommentReaction(arg1) {
  return window['go']['main']['App']['RemovePullCommentReaction'](arg1);
}

export function RemoveWorkspaceRepos(arg1) {
  return window['go']['main']['App']['RemoveWorkspaceRepos'](arg1);
}

export function RestorePullBranch(arg1) {
  return window['go']['main']['App']['RestorePullBranch'](arg1);
}

export function SetCheckUpdatesPref(arg1) {
  return window['go']['main']['App']['SetCheckUpdatesPref'](arg1);
}

export function SetGitBinaryPath(arg1) {
  return window['go']['main']['App']['SetGitBinaryPath'](arg1);
}

export function SetUserPrefs(arg1) {
  return window['go']['main']['App']['SetUserPrefs'](arg1);
}

export function SetWorkspace(arg1) {
  return window['go']['main']['App']['SetWorkspace'](arg1);
}

export function StarBranch(arg1) {
  return window['go']['main']['App']['StarBranch'](arg1);
}

export function StripGitBinaryQuarantine(arg1) {
  return window['go']['main']['App']['StripGitBinaryQuarantine'](arg1);
}

export function TestGitBinary(arg1) {
  return window['go']['main']['App']['TestGitBinary'](arg1);
}

export function UnstarBranch(arg1) {
  return window['go']['main']['App']['UnstarBranch'](arg1);
}

export function UpdatePullAssignee(arg1) {
  return window['go']['main']['App']['UpdatePullAssignee'](arg1);
}

export function UpdatePullBranch(arg1) {
  return window['go']['main']['App']['UpdatePullBranch'](arg1);
}

export function UpdatePullComment(arg1) {
  return window['go']['main']['App']['UpdatePullComment'](arg1);
}

export function UpdatePullLabels(arg1) {
  return window['go']['main']['App']['UpdatePullLabels'](arg1);
}

export function UpdatePullMilestone(arg1) {
  return window['go']['main']['App']['UpdatePullMilestone'](arg1);
}

export function UpdatePullReviewers(arg1) {
  return window['go']['main']['App']['UpdatePullReviewers'](arg1);
}

export function UpdatePullTitle(arg1) {
  return window['go']['main']['App']['UpdatePullTitle'](arg1);
}

export function UploadPullAttachment(arg1) {
  return window['go']['main']['App']['UploadPullAttachment'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
