// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {platform} from '../models';
import {git} from '../models';
import {gitbinary} from '../models';

export function AddProject(arg1:main.AddProjectArgs):Promise<main.AddProjectResult>;

export function AuthConnect(arg1:main.ConnectArgs):Promise<main.ConnectResult>;

export function AuthDisconnect(arg1:main.DisconnectArgs):Promise<void>;

export function AuthDisconnectOne(arg1:main.DisconnectOneArgs):Promise<void>;

export function AuthStatus():Promise<main.StatusResult>;

export function AuthSwitchAccount(arg1:main.SwitchAccountArgs):Promise<void>;

export function CloneRepo(arg1:main.CloneRepoArgs):Promise<main.CloneRepoResult>;

export function ClosePull(arg1:main.ClosePullArgs):Promise<platform.PullDetailDTO>;

export function CreateColumn(arg1:main.CreateColumnArgs):Promise<main.ColumnDTO>;

export function DeleteColumn(arg1:main.DeleteColumnArgs):Promise<void>;

export function FetchRepo(arg1:main.PullRepoArgs):Promise<main.FetchRepoResultDTO>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetCommitDetail(arg1:main.GetCommitDetailArgs):Promise<main.CommitDetailDTO>;

export function GetGitBinaryConfig():Promise<main.GitBinaryConfig>;

export function GetGitGraph(arg1:main.GetGitGraphArgs):Promise<main.GraphResultDTO>;

export function GetGitGraphAscii(arg1:main.GetGitGraphArgs):Promise<git.GraphLinesResult>;

export function GetPull(arg1:main.GetPullArgs):Promise<platform.PullDetailDTO>;

export function GetRepoById(arg1:main.GetRepoByIdArgs):Promise<main.GetRepoByIdResult>;

export function GetUserPrefs(arg1:main.GetUserPrefsArgs):Promise<Record<string, any>>;

export function GetWorkspace():Promise<main.WorkspaceInfo>;

export function IsRepoCloned(arg1:main.IsRepoClonedArgs):Promise<boolean>;

export function ListBranches(arg1:main.ListBranchesArgs):Promise<Array<main.BranchDTO>>;

export function ListColumns(arg1:main.ListColumnsArgs):Promise<Array<main.ColumnDTO>>;

export function ListIssues(arg1:main.ListIssuesArgs):Promise<Array<main.IssueDTO>>;

export function ListPulls(arg1:main.ListPullsArgs):Promise<main.PullListAppResp>;

export function ListRepos(arg1:main.ListReposArgs):Promise<main.ListReposResp>;

export function ListStarredBranches(arg1:main.ListStarredBranchesArgs):Promise<Array<string>>;

export function ListWorkspaceRepos():Promise<Array<Record<string, string>>>;

export function LogFrontend(arg1:main.LogFrontendArgs):Promise<void>;

export function LogGraph(arg1:main.LogGraphArgs):Promise<main.GraphResultDTO>;

export function MergePull(arg1:main.MergePullArgs):Promise<platform.PullDetailDTO>;

export function OpenDataDir():Promise<void>;

export function OpenGitBinaryPicker():Promise<string>;

export function PullRepo(arg1:main.PullRepoArgs):Promise<main.PullRepoResult>;

export function PullRepoByProjectId(arg1:main.PullRepoByProjectIdArgs):Promise<main.PullRepoResult>;

export function RemoveProject(arg1:main.RemoveProjectArgs):Promise<void>;

export function RemoveWorkspaceRepos(arg1:main.RemoveWorkspaceReposArgs):Promise<main.RemoveWorkspaceReposResult>;

export function SetGitBinaryPath(arg1:main.SetGitBinaryPathArgs):Promise<void>;

export function SetUserPrefs(arg1:main.SetUserPrefsArgs):Promise<Record<string, any>>;

export function SetWorkspace(arg1:main.SetWorkspaceArgs):Promise<void>;

export function StarBranch(arg1:main.StarBranchArgs):Promise<void>;

export function StripGitBinaryQuarantine(arg1:main.StripGitBinaryQuarantineArgs):Promise<void>;

export function TestGitBinary(arg1:main.SetGitBinaryPathArgs):Promise<gitbinary.TestGitResult>;

export function UnstarBranch(arg1:main.UnstarBranchArgs):Promise<void>;

export function UpdatePullAssignee(arg1:main.UpdatePullAssigneeArgs):Promise<platform.PullDetailDTO>;

export function UpdatePullLabels(arg1:main.UpdatePullLabelsArgs):Promise<platform.PullDetailDTO>;

export function UpdatePullReviewers(arg1:main.UpdatePullReviewersArgs):Promise<platform.PullDetailDTO>;
