// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function AuthConnect(arg1) {
  return window['go']['main']['App']['AuthConnect'](arg1);
}

export function AuthDisconnect(arg1) {
  return window['go']['main']['App']['AuthDisconnect'](arg1);
}

export function AuthDisconnectOne(arg1) {
  return window['go']['main']['App']['AuthDisconnectOne'](arg1);
}

export function AuthStatus() {
  return window['go']['main']['App']['AuthStatus']();
}

export function AuthSwitchAccount(arg1) {
  return window['go']['main']['App']['AuthSwitchAccount'](arg1);
}

export function CloneRepo(arg1) {
  return window['go']['main']['App']['CloneRepo'](arg1);
}

export function CreateColumn(arg1) {
  return window['go']['main']['App']['CreateColumn'](arg1);
}

export function DeleteColumn(arg1) {
  return window['go']['main']['App']['DeleteColumn'](arg1);
}

export function FetchRepo(arg1) {
  return window['go']['main']['App']['FetchRepo'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetCommitDetail(arg1) {
  return window['go']['main']['App']['GetCommitDetail'](arg1);
}

export function GetGitGraph(arg1) {
  return window['go']['main']['App']['GetGitGraph'](arg1);
}

export function GetGitGraphAscii(arg1) {
  return window['go']['main']['App']['GetGitGraphAscii'](arg1);
}

export function GetRepoById(arg1) {
  return window['go']['main']['App']['GetRepoById'](arg1);
}

export function GetUserPrefs(arg1) {
  return window['go']['main']['App']['GetUserPrefs'](arg1);
}

export function GetWorkspace() {
  return window['go']['main']['App']['GetWorkspace']();
}

export function IsRepoCloned(arg1) {
  return window['go']['main']['App']['IsRepoCloned'](arg1);
}

export function ListBranches(arg1) {
  return window['go']['main']['App']['ListBranches'](arg1);
}

export function ListColumns(arg1) {
  return window['go']['main']['App']['ListColumns'](arg1);
}

export function ListIssues(arg1) {
  return window['go']['main']['App']['ListIssues'](arg1);
}

export function ListRepos(arg1) {
  return window['go']['main']['App']['ListRepos'](arg1);
}

export function ListStarredBranches(arg1) {
  return window['go']['main']['App']['ListStarredBranches'](arg1);
}

export function ListWorkspaceRepos() {
  return window['go']['main']['App']['ListWorkspaceRepos']();
}

export function LogFrontend(arg1) {
  return window['go']['main']['App']['LogFrontend'](arg1);
}

export function LogGraph(arg1) {
  return window['go']['main']['App']['LogGraph'](arg1);
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function PullRepo(arg1) {
  return window['go']['main']['App']['PullRepo'](arg1);
}

export function PullRepoByProjectId(arg1) {
  return window['go']['main']['App']['PullRepoByProjectId'](arg1);
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function RemoveWorkspaceRepos(arg1) {
  return window['go']['main']['App']['RemoveWorkspaceRepos'](arg1);
}

export function SetUserPrefs(arg1) {
  return window['go']['main']['App']['SetUserPrefs'](arg1);
}

export function SetWorkspace(arg1) {
  return window['go']['main']['App']['SetWorkspace'](arg1);
}

export function StarBranch(arg1) {
  return window['go']['main']['App']['StarBranch'](arg1);
}

export function UnstarBranch(arg1) {
  return window['go']['main']['App']['UnstarBranch'](arg1);
}
