// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloneRepo(arg1) {
  return window['go']['main']['App']['CloneRepo'](arg1);
}

export function CreateColumn(arg1) {
  return window['go']['main']['App']['CreateColumn'](arg1);
}

export function DeleteColumn(arg1) {
  return window['go']['main']['App']['DeleteColumn'](arg1);
}

export function FetchRepo(arg1) {
  return window['go']['main']['App']['FetchRepo'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetCommitDetail(arg1) {
  return window['go']['main']['App']['GetCommitDetail'](arg1);
}

export function GetWorkspace() {
  return window['go']['main']['App']['GetWorkspace']();
}

export function ListBranches(arg1) {
  return window['go']['main']['App']['ListBranches'](arg1);
}

export function ListColumns(arg1) {
  return window['go']['main']['App']['ListColumns'](arg1);
}

export function ListIssues(arg1) {
  return window['go']['main']['App']['ListIssues'](arg1);
}

export function ListStarredBranches(arg1) {
  return window['go']['main']['App']['ListStarredBranches'](arg1);
}

export function ListWorkspaceRepos() {
  return window['go']['main']['App']['ListWorkspaceRepos']();
}

export function LogGraph(arg1) {
  return window['go']['main']['App']['LogGraph'](arg1);
}

export function PullRepo(arg1) {
  return window['go']['main']['App']['PullRepo'](arg1);
}

export function SetWorkspace(arg1) {
  return window['go']['main']['App']['SetWorkspace'](arg1);
}

export function StarBranch(arg1) {
  return window['go']['main']['App']['StarBranch'](arg1);
}

export function UnstarBranch(arg1) {
  return window['go']['main']['App']['UnstarBranch'](arg1);
}
